name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
